default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: gradurate_app_development
test:
  <<: *default
  database: gradurate_app_test
production:
  <<: *default
  database: gradurate_app_production
  username: gradurate_app
  password: <%= ENV['GRADURATE_APP_DATABASE_PASSWORD'] %>
